article/urls.py
from django.conf.urls import patterns, include, url
from api import ArticleResource

article_resource = ArticleResource()

urlpatterns = patterns('',
	url(r'^all/$', 'article.views.articles'),
	url(r'^get/(?P<article_id>\d+)/$', 'article.views.article'),
	url(r'^language/(?P<language>[a-z\-]+)/$', 'article.views.language'),
	url(r'^create/$', 'article.views.create'),
	url(r'^like/(?P<article_id>\d+)/$', 'article.views.like_article'),
	url(r'^add_comment/(?P<article_id>\d+)/$', 'article.views.add_comment'),
	url(r'^search/$', 'article.views.search_titles'),
	url(r'^api/', include(article_resource.urls)),
)

django_test/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_test.views.home', name='home'),
	    (r'^articles/', include('article.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django_test.views.login'),
    url(r'^accounts/auth/$', 'django_test.views.auth_view'),
    url(r'^accounts/logout/$', 'django_test.views.logout'),
    url(r'^accounts/loggedin/$', 'django_test.views.loggedin'),
    url(r'^accounts/invalid/$', 'django_test.views.invalid_login'),
    url(r'^accounts/register/$', 'django_test.views.register_user'),
    url(r'^accounts/register_success/$', 'django_test.views.register_success'),
)

article/models.py
from django.db import models
from time import time

def get_upload_file_name(instance, filename):
	return "uploaded_files/%s_%s" % (str(time()).replace('.','_'), filename)
# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length=200)
	body = models.TextField()
	pub_date = models.DateTimeField('date published')
	likes = models.IntegerField(default=0)
	thumbnail = models.FileField(upload_to=get_upload_file_name)
	
	def __unicode__(self):
		return self.title
		
class Comment(models.Model):
	first_name = models.CharField(max_length=200)
	second_name = models.CharField(max_length=200)
	body = models.TextField()
	pub_date = models.DateTimeField('date published')
	article = models.ForeignKey(Article)
	
	

article/forms.py
from django import forms
from models import Article, Comment

class ArticleForm(forms.ModelForm):
	
	class Meta:
		model = Article
		fields = ('title', 'body', 'pub_date', 'thumbnail')
		
class CommentForm(forms.ModelForm):
	
	class Meta:
		model = Comment
		fields = ('name', 'body')
		

django_test/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class MyRegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True)
	
	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')
		
		def save(self, commit=True):
			user = super(UserCreationForm, self).save(commit=False)
			user.set_password(self.cleaned_data["email"])
			
			if commit:
				user.save()
			return user

article/views.py
from django.shortcuts import render_to_response
from article.models import Article, Comment
from django.http import HttpResponse
from forms import ArticleForm, CommentForm
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from django.utils import timezone

def articles(request):
	language = 'en-gb'
	session_language = 'en-gb'
	
	if 'lang' in request.COOKIES:
		language = request.COOKIES['lang']
		
	if 'lang' in request.session:
		session_language = request.session['lang']
		
	args = {}
	args.update(csrf(request))
	
	args['articles'] = Article.objects.all()
	args['language'] = language
	args['session_language'] = session_language
		
	return render_to_response('articles.html',args)
	
	
def article(request, article_id=1):
	return render_to_response('article.html',
	{'article': Article.objects.get(id=article_id) })
	
def language(request, language='en-gb'):
	response = HttpResponse("setting language to %s" % language)
	
	response.set_cookie("lang", language)
	
	request.session['lang'] = language
	return response
	
def create(request):
	if request.POST:
		form = ArticleForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
		
			return HttpResponseRedirect('/articles/all')
		
	else:
		form = ArticleForm()
		
	args = {}
	args.update(csrf(request))
	
	args['form'] = form
	
	return render_to_response('create_article.html', args)
	
def like_article(request, article_id):
	if article_id:
		a = Article.objects.get(id=article_id)
		count = a.likes
		count += 1
		a.likes = count
		a.save()
		
	return HttpResponseRedirect('/articles/get/%s' % article_id)
	
def add_comment(request, article_id):
	a = Article.objects.get(id=article_id)
	
	if request.method == "POST":
		f = ComentForm(request.POST)
		if f.is_valid(commit=False):
			c.pub_date = timezone.now()
			c.article = a
			c.save()
		
		return HttpResponseRedirect('/articles/get/%s' % article_id)
		
	else:
		f = CommentForm()
		
	args = {}
	args.update(csrf(request))
	
	args['article'] = a
	args['form'] = f
	
	return render_to_response('add_comment.html', args)
	
def search_titles(request):
	if request.method == "POST":
		search_text = request.POST['search_text']
	else:
		search_text = ''
		
	articles = Article.objects.filter(title__contains=search_text)
	
	return render_to_response('ajax_search.html', {'articles' : articles})

django_test/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.core.context_processors import csrf
from forms import MyRegistrationForm

def login(request):
	c = {}
	c.update(csrf(request))
	return render_to_response('login.html', c)
	
def auth_view(request):
	username = request.POST.get('username', '')
	password = request.POST.get('password', '')
	user = auth.authenticate(username=username, password=password)
	
	if user is not None:
		auth.login(request, user)
		return HttpResponseRedirect('/accounts/loggedin')
	else:
		return HttpResponseRedirect('/accounts/invalid')
		
def loggedin(request):
	return render_to_response('loggedin.html', 
								{'full_name': request.user.username})
								
def invalid_login(request):
	return render_to_response('invalid_login.html')
	
def logout(request):
	auth.logout(request)
	return render_to_response('logout.html')
	
def register_user(request):
	if request.method == 'POST':
		form = MyRegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/accounts/register_success')
			
	args = {}
	args.update(csrf(request))
	
	args['form'] = MyRegistrationForm()
	print args
	return render_to_response('register.html', args)	
	
def register_success(request):
	return render_to_response('register_success.html')

article/templates/ajax_search.html
{% if articles.count > 0 %}

{% for article in articles %}
	<li><a href="/articles/get/{{ article.id }}/">{{ article.title }}</a></li>
{% endfor %}

{% else %}
<li>None to show!</li>

{% endif %}

article/templates/article.html
{% extends "base.html" %}

		{% block sidebar %}
		<ul>
			<li><a href="/articles/all">Articles</a></li>
		</ul>
		{% endblock %}
		
		
{% block content %}
<h1>{{ article.title }}</h1>
<P>{{ article.body }}</p>
{% if article.thumbnail %}
<p><img src="/static/assets/{{article.thumbnail}}" width="200"/></p>

{% endif %}
<p>{{article.likes}} people liked this article</a></p>
<p><a href="/articles/like/{{article.id}}">Like</a></p>

<h2>Comments</h2>
{% for c in article.comment_set.all %}
<p>{{c.name}}: {{c.body}}</p>
{% endfor %}

<p><a href="/articles/add_comment/{{article.id}}">Add Comment</a></p>


{% endblock %}

article/templates/articles.html
{% extends "base.html" %}

{% block sidebar %}
<ul>
	<li><a href="/articles/all">Articles</a></li>
	<li><a href="/articles/create">Create Articles</a></li>
</ul>

<h3>Search</h3>
{% csrf_token %}
<input type="text" id="search" name="search" />

<ul id="search-results">
	
</ul>

{% endblock %}

{% block content %}

<h2>Language is: {{language}}</h2>

<h2>Session Language is: {{session_language}}</h2>

{% if articles.count > 0 %}

{% for article in articles %}
<div>
<h2><a href="/articles/get/{{ article.id }}/">{{ article.title }}</a></h2>
<p>{{ article.body|lower|truncatewords:"10" }}</p>
<p>{{article.likes}} people liked this article</a></p>
</div>

{% endfor %}

{% else %}

<p> None to show!</p>

{% endif %}

{% endblock %}

article/templates/create_article.html
{% extends "base.html" %}

{% block sidebar %}
<ul>
	<li><a href="/articles/all">Cancel</a></li>
</ul>
{% endblock %}

{% block content %}
<form action="/articles/create/" method="post" enctype="multipart/form-data">{% csrf_token %}
<ul>
{{ form.as_ul }}
</ul>

<input type="submit" name="submit" value="Create Article">
</form>

{% endblock %}

article/templates/hello.html
<html>
<body>

Hi {{ name }},
this TEMPLATE seems to have worked!

</body>
</html>

article/templates/hello_class.html
<html>
<body>

Hi {{ name }},
this class based view TEMPLATE seems to have worked!

</body>
</html>

templates/article.html
<html>
<body>
<h1>{{ article.title }}</h1>
<P>{{ article.body }}</p>
</body>
</html>

templates/articles.html
<html>
<body>
<h1>Articles</h1>
{% for article in articles %}
<div>
<h2><a href="/articles/get/{{ article.id }}/">{{ article.title }}</a></h2>
<p>{{ article.body|upper|truncatewords:"10" }}</p>
{% endfor %}
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %} My Base Template{% endblock %}</title>	
	
	<link rel="stylesheet" type="text/css" href="{% static "assets/css/default.css" %}">
	
	<script src="{% static "assets/js/jquery-2.1.1.min.js" %}"></script>
	<script src="{% static "assets/js/ajax.js" %}"></script>
				
</head>
<body>
	<div id="page">
	<div id="sidebar">
		{% block sidebar %}
		<ul>
			<li><a href="/articles/all">Articles</a></li>
			<li><a href="/admin/">Admin</a></li>
		</ul>
		{% endblock %}
	</div>
	<div id="content">
		{% block content %}This is the content area{% endblock %}		
		<img src="{% static "assets/images/Python-logo.png" %}" width="100"/>
	</div>	
	</div>	
</body>
</html>

templates/hello.html
<html>
<body>

Hi {{ name }},
this TEMPLATE seems to have worked!

</body>
</html>

templates/hello_class.html
<html>
<body>

Hi {{ name }},
this class based view TEMPLATE seems to have worked!

</body>
</html>

templates/invalid_login.html
{% extends "base.html" %}

{% block content %}

	<h2>Your password or name is wrong! Please try again!</h2>
	<p>Click <a href="/accounts/login/">here</a> to login page.</p>
	
{% endblock %}

templates/loggedin.html
{% extends "base.html" %}

{% block content %}

	<h2>Hi {{full_name}} you are Logged in!</h2>
	<p>Click <a href="/accounts/logout/">here</a> to logout.</p>
	
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}

	{% if form.errors %}
		<p class="error">Sorry, that's not a valid username or password</p>
	{% endif %}
	
	<form action="/accounts/auth/" method="post">{% csrf_token %}
		<label for="username">User name:</label>
		<input type="text" name="username" value="" id="username">
		<label for="password">Password:</label>
		<input type="password" name="password" value="" id="password">
		
		<input type="submit" value="login" />
		
	</form>
	
{% endblock %}

templates/logout.html
{% extends "base.html" %}

{% block content %}

	<h2>Logged out!</h2>
	<p>Click <a href="/accounts/login/">here</a> to login</p>
	
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}

	<h2>Register</h2>
	<form action="/accounts/register/" method="post">{% csrf_token %}
	{{form}}
	
	<input type="submit" value="Register" />
	
	</form>
	
{% endblock %}

templates/register_success.html
{% extends "base.html" %}

{% block content %}

	<h2>You have registered!</h2>
	<p>Click <a href="/accounts/login/">here</a>to login again</p>
	
{% endblock %}